### ISSUE TITLE
Fake tier 3 judge

### ISSUE THREAD

**Issue by vuthanhtrung2010** [VNOI-Admin/OJ#403]
Tôi đang sử dụng **tier 3** judge với config sau

```yaml
id: trung
key: "q+Wawg0bPZiv6k+i6pOUozcsJOGK5VfSJu1OGogx2u7dPbO6XFZBPtJ2NYUNFo+Qm8QSG0P2CPVv1ITUgnHZnXsSo9R19wfWmpk2"
problem_storage_globs:
  - /problems/*
runtime:
  ccl: /opt/ccl/lx86cl
  sed: /bin/sed
  awk: /usr/bin/awk
  gnatmake: /usr/bin/gnatmake
  chicken-csc: /usr/bin/csc
  dart: /opt/dart-sdk/bin/dart
  tclsh: /usr/bin/tclsh
  cobc: /usr/bin/cobc
  erl: /usr/bin/erl
  erlc: /usr/bin/erlc
  tprolog: /opt/turing/tprolog/tprolog
  tprologc: /opt/turing/tprolog/tprologc
  turing_dir: /opt/turing/tprolog
  node: /usr/bin/node
  lua: /usr/bin/lua
  ocaml: /usr/bin/ocamlopt
  pypy: /opt/pypy/bin/pypy
  pypydir: /opt/pypy/
  pypy3: /opt/pypy3/bin/pypy
  pypy3dir: /opt/pypy3/
  ghc: /usr/bin/ghc
  go: /usr/bin/go
  fsharpc: /usr/bin/fsharpc
  mono-csc: /usr/bin/mono-csc
  mono-vbnc: /usr/bin/vbnc
  mono: /usr/bin/mono
  dmd: /usr/bin/dmd
  fpc: /opt/fpc-2.6.4/bin/fpc
  clang: /usr/bin/clang
  clang++: /usr/bin/clang++
  gcc: /usr/bin/gcc
  g++: /usr/bin/g++
  g++11: /usr/bin/g++
  g++14: /opt/gcc-5.1.0/bin/g++
  gfortran: /usr/bin/gfortran
  nasm: /usr/bin/nasm
  ld: /usr/bin/ld
  python: /opt/python27/bin/python2.7
  python2dir: /opt/python27/
  python3: /opt/python34/bin/python3.4
  python3dir: /opt/python34/
  java: /usr/bin/java
  javac: /usr/bin/javac
  java8: /usr/lib/jvm/jdk-8-oracle-i586/bin/java
  javac8: /usr/lib/jvm/jdk-8-oracle-i586/bin/javac
# Custom V8 build to facilitate online judging: https://github.com/DMOJ/v8dmoj
  v8dmoj: /home/judge/judge/executors/v8dmoj
  php: /usr/bin/php
  phpconfdir: /etc/php5/
  perl: /usr/bin/perl
  ruby19: /usr/bin/ruby1.9.1
  ruby21: /usr/bin/ruby
  racket: /opt/racket/bin/racket
  raco: /opt/racket/bin/raco
  racket-lib: /opt/racket/lib
  gnustep-config: /usr/bin/gnustep-config
  gobjc: /usr/bin/gcc
```

Command tôi chạy run **tier 3**

![image](https://github.com/user-attachments/assets/963aa3a7-a6ad-4724-ac8a-a6796cca9623)
Khi sử dụng chỉ chạy đc **1 số ngôn ngữ**

![image](https://github.com/user-attachments/assets/ccfa5690-b1d5-496d-a773-126a2bc093be)
Trong khi test passed? **Sao nó ko test CPP 20 và CPP 17?**

![image](https://github.com/user-attachments/assets/ba228c6e-89a7-44c5-8bcf-10808e952c41)
Và khi exec trong docker container **sử dụng CPP20**:

![image](https://github.com/user-attachments/assets/5811a7e7-75f3-49a4-a574-015021a24b3d)

Please fix

Tôi chạy ```make judge-tier3``` rồi command docker run.

https://github.com/VNOI-Admin/judge-server Đang sử dụng repo này. Latest
